#include "Engine_Defines.h"

BEGIN(Engine)

const D3D12_INPUT_ELEMENT_DESC VTXPOS::VertexElements[] = {
	{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }, /* Position */
};

const D3D12_INPUT_ELEMENT_DESC VTXPOSNOR::VertexElements[] = {
{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }, /* Position */
{ "NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }, /* Normal*/
};

END